### PR TITLE
Should fix HTTPS issue

### PR DESCRIPTION
**Pull request by grunsab**
https://www.dropbox.com/s/oqyzcnoaz5k40qc/Screenshot%202015-02-07%2015.48.29.png?dl=0

### CODE REVIEW

**Comment by staringispolite** [comment]
Ahhh I always forget about this. I'm actually going to just do a protocol-less include (no http OR https)

**Comment by grunsab** [comment]
http://blog.httpwatch.com/2010/02/10/using-protocol-relative-urls-to-switch-between-http-and-https/

So not this?

**Comment by staringispolite** [comment]
Same as that just different term (protocol-less vs protocol-relative)

**Comment by staringispolite** [comment]
Thanks for finding the issue! Closing this PR

**Pull request closed without merging**
